[package]
name = "libkrime"
version = "0.1.0"
edition = "2021"

authors = [
    "William Brown <william@blackhats.net.au>",
]
rust-version = "1.77"
license = "MPL-2.0"
homepage = "https://github.com/Firstyear/libkrimes"
repository = "https://github.com/Firstyear/libkrimes"

[dependencies]
